### ISSUE TITLE
[Suggestion] Using poetry to publish toCase in pypi

### ISSUE THREAD

**Issue by kishaningithub** [RickBarretto/toCase#1]
IMO Poetry makes it very seamless to publish packages to pypi and also to manage deps (if any)

https://python-poetry.org/

This way you can get rid of setup.py and just use a toml file and publish to pypi with a single command :-)

**Comment by RickBarretto** [comment]
I'll add poetry support soon. Thank you!

**Comment by RickBarretto** [comment]
Added! See [Install Instruction](https://github.com/RickBarretto/toCase#installing)
