### ISSUE TITLE
Importing causes an error

### ISSUE THREAD

**Issue by kishaningithub** [RickBarretto/toCase#2]
https://github.com/RickBarretto/toCase/blob/b9edf6bc679d7e1c98943bdc1f699e0face8f820/toCase/tocase.py#L340

This particular line causes an exception upon import

```
Traceback (most recent call last):
  File "toCase/toCase/tocase.py", line 340, in <module>
    print(Case.toCamel("helloworld"))
  File "toCase/toCase/tocase.py", line 64, in toCamel
    Case._Error()
  File "toCase/toCase/tocase.py", line 34, in _Error
    raise ValueError("case is wrong, choose between: 'lower', 'upper' or 'title'")
ValueError: case is wrong, choose between: 'lower', 'upper' or 'title'
```

**Comment by RickBarretto** [comment]
It can't convert a pure lowcase to a Camel because it doesn't have sense.
As the the exception raised, use `Case.lower()`, `Case.upper()` or `Case.title()`.

I got a time that I don't change this project, but I'll check if it have any error...
But, for while, try to use this that I said.

**Comment by RickBarretto** [comment]
I'll check it in now! 
It was a test that I forget to remove. 😄

**Comment by RickBarretto** [comment]
Fixed!
